//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HearThisTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HearThisTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Septuagint&quot;
        ///# Version=1.6
        ///# 
        ///# modifications by Studge 26/ June/ 2009
        ///# This should include the versifications for Bibles which follow LXX versificatio mainly Orthodox Bibles. [Studge]
        ///#
        ///# List of books, chapters, verses
        ///# One line per book.
        ///# One entry for each chapter.
        ///# Verse number is the maximum verse number for that chapter.
        ///# See the lines containing =&apos;s below for verse mappings.
        ///#
        ///# modifications by Reinier 20/ April/ 2010
        ///# all data that are not part of the LXX itself [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeptuagintVersification {
            get {
                return ResourceManager.GetString("SeptuagintVersification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Vulgate&quot;
        ///# Version=1.4
        ///# 
        ///# modifications by Studge 26/June/2009
        ///# this is for Bibles which follow the versification of the Vulgate, mainly Catholic Bibles
        ///# therefore this includes deuterocanonical books from Vulgate and Latin manuscripts
        ///# Vulgate projects in Paratext are VUL83 (Stuttgart text) and NVL98 (Nova Vulgata) [Studge]
        ///#
        ///# mapping for XXA -&gt; PSA has been deleted  [requested by RdB - Barb]
        ///# XXB has been moved to LAO [Barb] Jan 2011
        ///#
        ///# No mapping done for TOB, JDT and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VulgateVersification {
            get {
                return ResourceManager.GetString("VulgateVersification", resourceCulture);
            }
        }
    }
}
