var annotated_dup =
[
    [ "HearThis", "namespace_hear_this.html", [
      [ "Communication", "namespace_hear_this_1_1_communication.html", [
        [ "IAndroidLink", "interface_hear_this_1_1_communication_1_1_i_android_link.html", null ],
        [ "WindowsLink", "class_hear_this_1_1_communication_1_1_windows_link.html", null ]
      ] ],
      [ "Publishing", "namespace_hear_this_1_1_publishing.html", [
        [ "AudiBibleEncoder", "class_hear_this_1_1_publishing_1_1_audi_bible_encoder.html", null ],
        [ "AudiBiblePublishingMethod", "class_hear_this_1_1_publishing_1_1_audi_bible_publishing_method.html", null ],
        [ "BunchOfFilesPublishingMethod", "class_hear_this_1_1_publishing_1_1_bunch_of_files_publishing_method.html", null ],
        [ "FlacEncoder", "class_hear_this_1_1_publishing_1_1_flac_encoder.html", null ],
        [ "HierarchicalPublishingMethodBase", "class_hear_this_1_1_publishing_1_1_hierarchical_publishing_method_base.html", null ],
        [ "IAudioEncoder", "interface_hear_this_1_1_publishing_1_1_i_audio_encoder.html", null ],
        [ "IClipFile", "interface_hear_this_1_1_publishing_1_1_i_clip_file.html", "interface_hear_this_1_1_publishing_1_1_i_clip_file" ],
        [ "IPublishingInfoProvider", "interface_hear_this_1_1_publishing_1_1_i_publishing_info_provider.html", null ],
        [ "IPublishingMethod", "interface_hear_this_1_1_publishing_1_1_i_publishing_method.html", null ],
        [ "IRecordingAvailability", "interface_hear_this_1_1_publishing_1_1_i_recording_availability.html", null ],
        [ "KulumiPublishingMethod", "class_hear_this_1_1_publishing_1_1_kulumi_publishing_method.html", "class_hear_this_1_1_publishing_1_1_kulumi_publishing_method" ],
        [ "LameEncoder", "class_hear_this_1_1_publishing_1_1_lame_encoder.html", null ],
        [ "MegaVoicePublishingMethod", "class_hear_this_1_1_publishing_1_1_mega_voice_publishing_method.html", null ],
        [ "OggEncoder", "class_hear_this_1_1_publishing_1_1_ogg_encoder.html", null ],
        [ "OpusEncoder", "class_hear_this_1_1_publishing_1_1_opus_encoder.html", null ],
        [ "PublishDialog", "class_hear_this_1_1_publishing_1_1_publish_dialog.html", "class_hear_this_1_1_publishing_1_1_publish_dialog" ],
        [ "PublishingMethodBase", "class_hear_this_1_1_publishing_1_1_publishing_method_base.html", "class_hear_this_1_1_publishing_1_1_publishing_method_base" ],
        [ "PublishingModel", "class_hear_this_1_1_publishing_1_1_publishing_model.html", "class_hear_this_1_1_publishing_1_1_publishing_model" ],
        [ "SaberPublishingMethod", "class_hear_this_1_1_publishing_1_1_saber_publishing_method.html", null ],
        [ "ScriptureAppBuilderPublishingMethod", "class_hear_this_1_1_publishing_1_1_scripture_app_builder_publishing_method.html", null ],
        [ "WavEncoder", "class_hear_this_1_1_publishing_1_1_wav_encoder.html", null ]
      ] ],
      [ "Script", "namespace_hear_this_1_1_script.html", [
        [ "BibleStats", "class_hear_this_1_1_script_1_1_bible_stats.html", null ],
        [ "BibleStatsBase", "class_hear_this_1_1_script_1_1_bible_stats_base.html", "class_hear_this_1_1_script_1_1_bible_stats_base" ],
        [ "Book", "class_hear_this_1_1_script_1_1_book.html", null ],
        [ "BookInfo", "class_hear_this_1_1_script_1_1_book_info.html", "class_hear_this_1_1_script_1_1_book_info" ],
        [ "Chapter", "class_hear_this_1_1_script_1_1_chapter.html", null ],
        [ "ChapterInfo", "class_hear_this_1_1_script_1_1_chapter_info.html", "class_hear_this_1_1_script_1_1_chapter_info" ],
        [ "ChapterRecordingInfoBase", "class_hear_this_1_1_script_1_1_chapter_recording_info_base.html", null ],
        [ "Chunk", "class_hear_this_1_1_script_1_1_chunk.html", null ],
        [ "ExtraRecordingInfo", "class_hear_this_1_1_script_1_1_extra_recording_info.html", null ],
        [ "FullyRecordedStatus", "class_hear_this_1_1_script_1_1_fully_recorded_status.html", null ],
        [ "HearThisPackMaker", "class_hear_this_1_1_script_1_1_hear_this_pack_maker.html", null ],
        [ "HearThisPackReader", "class_hear_this_1_1_script_1_1_hear_this_pack_reader.html", "class_hear_this_1_1_script_1_1_hear_this_pack_reader" ],
        [ "IActorCharacterProvider", "interface_hear_this_1_1_script_1_1_i_actor_character_provider.html", null ],
        [ "IBibleStats", "interface_hear_this_1_1_script_1_1_i_bible_stats.html", "interface_hear_this_1_1_script_1_1_i_bible_stats" ],
        [ "IncompatibleFileVersionException", "class_hear_this_1_1_script_1_1_incompatible_file_version_exception.html", null ],
        [ "IncompatibleProjectDataVersionException", "class_hear_this_1_1_script_1_1_incompatible_project_data_version_exception.html", null ],
        [ "IScriptProvider", "interface_hear_this_1_1_script_1_1_i_script_provider.html", "interface_hear_this_1_1_script_1_1_i_script_provider" ],
        [ "IScripture", "interface_hear_this_1_1_script_1_1_i_scripture.html", "interface_hear_this_1_1_script_1_1_i_scripture" ],
        [ "IScrParserState", "interface_hear_this_1_1_script_1_1_i_scr_parser_state.html", "interface_hear_this_1_1_script_1_1_i_scr_parser_state" ],
        [ "IScrProjectSettings", "interface_hear_this_1_1_script_1_1_i_scr_project_settings.html", "interface_hear_this_1_1_script_1_1_i_scr_project_settings" ],
        [ "IScrProjectSettingsProvider", "interface_hear_this_1_1_script_1_1_i_scr_project_settings_provider.html", null ],
        [ "IScrVerseIterationHelper", "interface_hear_this_1_1_script_1_1_i_scr_verse_iteration_helper.html", null ],
        [ "ISkippedStyleInfoProvider", "interface_hear_this_1_1_script_1_1_i_skipped_style_info_provider.html", null ],
        [ "IStyleInfoProvider", "interface_hear_this_1_1_script_1_1_i_style_info_provider.html", null ],
        [ "MigrationProgressTracker", "class_hear_this_1_1_script_1_1_migration_progress_tracker.html", "class_hear_this_1_1_script_1_1_migration_progress_tracker" ],
        [ "MultiVoiceBlock", "class_hear_this_1_1_script_1_1_multi_voice_block.html", null ],
        [ "MultiVoiceBook", "class_hear_this_1_1_script_1_1_multi_voice_book.html", null ],
        [ "MultiVoiceChapter", "class_hear_this_1_1_script_1_1_multi_voice_chapter.html", null ],
        [ "MultiVoiceScriptProvider", "class_hear_this_1_1_script_1_1_multi_voice_script_provider.html", "class_hear_this_1_1_script_1_1_multi_voice_script_provider" ],
        [ "ParatextParagraph", "class_hear_this_1_1_script_1_1_paratext_paragraph.html", "class_hear_this_1_1_script_1_1_paratext_paragraph" ],
        [ "ParatextProjectProxy", "class_hear_this_1_1_script_1_1_paratext_project_proxy.html", null ],
        [ "ParatextScriptProvider", "class_hear_this_1_1_script_1_1_paratext_script_provider.html", "class_hear_this_1_1_script_1_1_paratext_script_provider" ],
        [ "ParatextVersificationInfo", "class_hear_this_1_1_script_1_1_paratext_versification_info.html", null ],
        [ "ParserState", "class_hear_this_1_1_script_1_1_parser_state.html", "class_hear_this_1_1_script_1_1_parser_state" ],
        [ "Project", "class_hear_this_1_1_script_1_1_project.html", "class_hear_this_1_1_script_1_1_project" ],
        [ "ProjectSettings", "class_hear_this_1_1_script_1_1_project_settings.html", "class_hear_this_1_1_script_1_1_project_settings" ],
        [ "RangesToBreakByVerse", "class_hear_this_1_1_script_1_1_ranges_to_break_by_verse.html", null ],
        [ "Recording", "class_hear_this_1_1_script_1_1_recording.html", null ],
        [ "Recordings", "class_hear_this_1_1_script_1_1_recordings.html", null ],
        [ "RepoMerger", "class_hear_this_1_1_script_1_1_repo_merger.html", "class_hear_this_1_1_script_1_1_repo_merger" ],
        [ "SampleScriptProvider", "class_hear_this_1_1_script_1_1_sample_script_provider.html", "class_hear_this_1_1_script_1_1_sample_script_provider" ],
        [ "ScriptLine", "class_hear_this_1_1_script_1_1_script_line.html", "class_hear_this_1_1_script_1_1_script_line" ],
        [ "ScriptLineIdentifier", "class_hear_this_1_1_script_1_1_script_line_identifier.html", "class_hear_this_1_1_script_1_1_script_line_identifier" ],
        [ "ScriptProviderBase", "class_hear_this_1_1_script_1_1_script_provider_base.html", "class_hear_this_1_1_script_1_1_script_provider_base" ],
        [ "ScriptureRange", "class_hear_this_1_1_script_1_1_scripture_range.html", "class_hear_this_1_1_script_1_1_scripture_range" ],
        [ "SentenceClauseSplitter", "class_hear_this_1_1_script_1_1_sentence_clause_splitter.html", null ],
        [ "ShiftClipsViewModel", "class_hear_this_1_1_script_1_1_shift_clips_view_model.html", null ],
        [ "SkippedScriptLines", "class_hear_this_1_1_script_1_1_skipped_script_lines.html", null ],
        [ "StyleLookup", "class_hear_this_1_1_script_1_1_style_lookup.html", null ]
      ] ],
      [ "StringDifferences", "namespace_hear_this_1_1_string_differences.html", [
        [ "StringDifferenceFinder", "class_hear_this_1_1_string_differences_1_1_string_difference_finder.html", "class_hear_this_1_1_string_differences_1_1_string_difference_finder" ],
        [ "StringDifferenceSegment", "class_hear_this_1_1_string_differences_1_1_string_difference_segment.html", null ]
      ] ],
      [ "UI", "namespace_hear_this_1_1_u_i.html", [
        [ "ActorCharacterChooser", "class_hear_this_1_1_u_i_1_1_actor_character_chooser.html", "class_hear_this_1_1_u_i_1_1_actor_character_chooser" ],
        [ "AdministrativeSettings", "class_hear_this_1_1_u_i_1_1_administrative_settings.html", "class_hear_this_1_1_u_i_1_1_administrative_settings" ],
        [ "AlertImpl", "class_hear_this_1_1_u_i_1_1_alert_impl.html", null ],
        [ "AndroidSyncDialog", "class_hear_this_1_1_u_i_1_1_android_sync_dialog.html", "class_hear_this_1_1_u_i_1_1_android_sync_dialog" ],
        [ "ArrowButton", "class_hear_this_1_1_u_i_1_1_arrow_button.html", null ],
        [ "AudioButtonsControl", "class_hear_this_1_1_u_i_1_1_audio_buttons_control.html", "class_hear_this_1_1_u_i_1_1_audio_buttons_control" ],
        [ "BookButton", "class_hear_this_1_1_u_i_1_1_book_button.html", "class_hear_this_1_1_u_i_1_1_book_button" ],
        [ "ChapterButton", "class_hear_this_1_1_u_i_1_1_chapter_button.html", "class_hear_this_1_1_u_i_1_1_chapter_button" ],
        [ "CheckableItem", "class_hear_this_1_1_u_i_1_1_checkable_item.html", null ],
        [ "ChooseProject", "class_hear_this_1_1_u_i_1_1_choose_project.html", "class_hear_this_1_1_u_i_1_1_choose_project" ],
        [ "CustomButton", "class_hear_this_1_1_u_i_1_1_custom_button.html", "class_hear_this_1_1_u_i_1_1_custom_button" ],
        [ "DataMigrationReportNagDlg", "class_hear_this_1_1_u_i_1_1_data_migration_report_nag_dlg.html", "class_hear_this_1_1_u_i_1_1_data_migration_report_nag_dlg" ],
        [ "DiscontiguousProgressTrackBar", "class_hear_this_1_1_u_i_1_1_discontiguous_progress_track_bar.html", "class_hear_this_1_1_u_i_1_1_discontiguous_progress_track_bar" ],
        [ "ExclamationIcon", "class_hear_this_1_1_u_i_1_1_exclamation_icon.html", null ],
        [ "ExistingProjectsList", "class_hear_this_1_1_u_i_1_1_existing_projects_list.html", "class_hear_this_1_1_u_i_1_1_existing_projects_list" ],
        [ "HearThisToolbarButton", "class_hear_this_1_1_u_i_1_1_hear_this_toolbar_button.html", "class_hear_this_1_1_u_i_1_1_hear_this_toolbar_button" ],
        [ "ILocalizable", "interface_hear_this_1_1_u_i_1_1_i_localizable.html", "interface_hear_this_1_1_u_i_1_1_i_localizable" ],
        [ "MergeProgressDialog", "class_hear_this_1_1_u_i_1_1_merge_progress_dialog.html", "class_hear_this_1_1_u_i_1_1_merge_progress_dialog" ],
        [ "PlayButton", "class_hear_this_1_1_u_i_1_1_play_button.html", null ],
        [ "RecordButton", "class_hear_this_1_1_u_i_1_1_record_button.html", "class_hear_this_1_1_u_i_1_1_record_button" ],
        [ "RecordingToolControl", "class_hear_this_1_1_u_i_1_1_recording_tool_control.html", "class_hear_this_1_1_u_i_1_1_recording_tool_control" ],
        [ "RecordInPartsDlg", "class_hear_this_1_1_u_i_1_1_record_in_parts_dlg.html", "class_hear_this_1_1_u_i_1_1_record_in_parts_dlg" ],
        [ "SaveHearThisPackDlg", "class_hear_this_1_1_u_i_1_1_save_hear_this_pack_dlg.html", "class_hear_this_1_1_u_i_1_1_save_hear_this_pack_dlg" ],
        [ "ScriptControl", "class_hear_this_1_1_u_i_1_1_script_control.html", "class_hear_this_1_1_u_i_1_1_script_control" ],
        [ "ScriptTextHasChangedControl", "class_hear_this_1_1_u_i_1_1_script_text_has_changed_control.html", "class_hear_this_1_1_u_i_1_1_script_text_has_changed_control" ],
        [ "SegmentPaintInfo", "class_hear_this_1_1_u_i_1_1_segment_paint_info.html", null ],
        [ "SelectBundleDlg", "class_hear_this_1_1_u_i_1_1_select_bundle_dlg.html", null ],
        [ "Shell", "class_hear_this_1_1_u_i_1_1_shell.html", "class_hear_this_1_1_u_i_1_1_shell" ],
        [ "ShiftClipsDlg", "class_hear_this_1_1_u_i_1_1_shift_clips_dlg.html", "class_hear_this_1_1_u_i_1_1_shift_clips_dlg" ],
        [ "UnitNavigationButton", "class_hear_this_1_1_u_i_1_1_unit_navigation_button.html", null ],
        [ "UpgradeNeededDialog", "class_hear_this_1_1_u_i_1_1_upgrade_needed_dialog.html", "class_hear_this_1_1_u_i_1_1_upgrade_needed_dialog" ]
      ] ],
      [ "RecordingAvailability", "class_hear_this_1_1_recording_availability.html", null ],
      [ "WhitespaceCharacter", "class_hear_this_1_1_whitespace_character.html", null ]
    ] ],
    [ "HearThisTests", "namespace_hear_this_tests.html", [
      [ "Utils", "namespace_hear_this_tests_1_1_utils.html", [
        [ "StringDifferences", "namespace_hear_this_tests_1_1_utils_1_1_string_differences.html", [
          [ "StringDifferenceFinderTests", "class_hear_this_tests_1_1_utils_1_1_string_differences_1_1_string_difference_finder_tests.html", null ]
        ] ]
      ] ],
      [ "AudiBiblePublishingMethodTests", "class_hear_this_tests_1_1_audi_bible_publishing_method_tests.html", null ],
      [ "BibleStatsTests", "class_hear_this_tests_1_1_bible_stats_tests.html", null ],
      [ "BookChap", "class_hear_this_tests_1_1_book_chap.html", null ],
      [ "ChapterInfoTests", "class_hear_this_tests_1_1_chapter_info_tests.html", "class_hear_this_tests_1_1_chapter_info_tests" ],
      [ "ClipFakeProvider", "class_hear_this_tests_1_1_clip_fake_provider.html", "class_hear_this_tests_1_1_clip_fake_provider" ],
      [ "ClipRepositoryCharacterFilterTests", "class_hear_this_tests_1_1_clip_repository_character_filter_tests.html", null ],
      [ "ClipRepositoryTests", "class_hear_this_tests_1_1_clip_repository_tests.html", "class_hear_this_tests_1_1_clip_repository_tests" ],
      [ "DiscontiguousProgressTrackBarTests", "class_hear_this_tests_1_1_discontiguous_progress_track_bar_tests.html", null ],
      [ "FakeLink", "class_hear_this_tests_1_1_fake_link.html", null ],
      [ "FakeProvider", "class_hear_this_tests_1_1_fake_provider.html", "class_hear_this_tests_1_1_fake_provider" ],
      [ "FakeRecordingAvailability", "class_hear_this_tests_1_1_fake_recording_availability.html", null ],
      [ "FakeVerseInfo", "class_hear_this_tests_1_1_fake_verse_info.html", "class_hear_this_tests_1_1_fake_verse_info" ],
      [ "FakeVerseInfo2", "class_hear_this_tests_1_1_fake_verse_info2.html", "class_hear_this_tests_1_1_fake_verse_info2" ],
      [ "HearThisPackMakerTests", "class_hear_this_tests_1_1_hear_this_pack_maker_tests.html", null ],
      [ "LinkLabelHelperTests", "class_hear_this_tests_1_1_link_label_helper_tests.html", "class_hear_this_tests_1_1_link_label_helper_tests" ],
      [ "MegaVoicePublishingMethodTests", "class_hear_this_tests_1_1_mega_voice_publishing_method_tests.html", null ],
      [ "MergerWithBlockTracking", "class_hear_this_tests_1_1_merger_with_block_tracking.html", "class_hear_this_tests_1_1_merger_with_block_tracking" ],
      [ "MergerWithChapterTracking", "class_hear_this_tests_1_1_merger_with_chapter_tracking.html", "class_hear_this_tests_1_1_merger_with_chapter_tracking" ],
      [ "MockEncoder", "class_hear_this_tests_1_1_mock_encoder.html", null ],
      [ "MultiVoiceScriptProviderTests", "class_hear_this_tests_1_1_multi_voice_script_provider_tests.html", "class_hear_this_tests_1_1_multi_voice_script_provider_tests" ],
      [ "ParatextParagraphTests", "class_hear_this_tests_1_1_paratext_paragraph_tests.html", "class_hear_this_tests_1_1_paratext_paragraph_tests" ],
      [ "ParatextScriptProviderTests", "class_hear_this_tests_1_1_paratext_script_provider_tests.html", "class_hear_this_tests_1_1_paratext_script_provider_tests" ],
      [ "ParatextVersificationInfoTests", "class_hear_this_tests_1_1_paratext_versification_info_tests.html", null ],
      [ "PathData", "class_hear_this_tests_1_1_path_data.html", null ],
      [ "PathPair", "class_hear_this_tests_1_1_path_pair.html", null ],
      [ "ProjectTests", "class_hear_this_tests_1_1_project_tests.html", null ],
      [ "PublishingModelTests", "class_hear_this_tests_1_1_publishing_model_tests.html", null ],
      [ "RepoMergerTests", "class_hear_this_tests_1_1_repo_merger_tests.html", "class_hear_this_tests_1_1_repo_merger_tests" ],
      [ "ScriptLinePainterTests", "class_hear_this_tests_1_1_script_line_painter_tests.html", "class_hear_this_tests_1_1_script_line_painter_tests" ],
      [ "ScriptProviderBaseTests", "class_hear_this_tests_1_1_script_provider_base_tests.html", null ],
      [ "ScriptureAppBuilderPublishingMethodTests", "class_hear_this_tests_1_1_scripture_app_builder_publishing_method_tests.html", null ],
      [ "SentenceClauseSplitterTests", "class_hear_this_tests_1_1_sentence_clause_splitter_tests.html", null ],
      [ "SkippedScriptLinesTests", "class_hear_this_tests_1_1_skipped_script_lines_tests.html", null ],
      [ "TestPublisher", "class_hear_this_tests_1_1_test_publisher.html", "class_hear_this_tests_1_1_test_publisher" ],
      [ "TextBundleScriptureTests", "class_hear_this_tests_1_1_text_bundle_scripture_tests.html", null ]
    ] ]
];